### ISSUE TITLE
concurrent execution

### ISSUE THREAD

**Issue by mccraigmccraig** [funcool/cats-channel#2]
while working on a version of canal for manifold/Deferred instead of core.async/chan [(defurred)](https://github.com/employeerepublic/defurred) i realised that there is a sync point in between each step of a multi-step canal or deferred operation

it would be nice if there were a way to achieve concurrent execution like manifold's [let-flow](https://github.com/ztellman/manifold/blob/master/docs/deferred.md#let-flow) does, but i can't think of how

as far as i can see let-flow [extracts a dependency graph](https://github.com/ztellman/manifold/blob/master/src/manifold/deferred.clj#L1227) from the bindings and steps and creates a tree of deferred dependencies to realise that graph concurrently, but i can't see any way to do this within the monad structure

maybe i'm just being blind because i'm a monad noob

do you have any ideas ?

**Comment by ghost** [comment]
> while working on a version of canal for manifold/Deferred instead of core.async/chan (defurred) i realised that there is a sync point in between each step of a multi-step canal or deferred operation

Yes, monadic bind is inherently sequential.

> it would be nice if there were a way to achieve concurrent execution like manifold's let-flow does, but i can't think of how

We're currently working on [adding applicative do notation](https://github.com/funcool/cats/pull/63) to cats, which will have the same result as `let-flow` but is more generic.

> as far as i can see let-flow extracts a dependency graph from the bindings and steps and creates a tree of deferred dependencies to realise that graph concurrently, but i can't see any way to do this within the monad structure

This can be done with applicatives but not with monads, and that's exactly how the work in progress `alet` macro works.

> maybe i'm just being blind because i'm a monad noob

Not at all, looks like you've grasped them quite well!
